### ISSUE TITLE
Wordchains can end up having the same word in them multiple times

### ISSUE THREAD

**Issue by agincel** [AlexMassenzio/wordchain#16]
### Describe the bug

On 12/5, the same word was included in the chain 3 times. Some checks should probably be in place to prevent the same word from being chosen more than once.

### Reproduction

Play current wordchain on 12/5.

### System Info

```Shell
Windows 10, Firefox
```

**Comment by cbouwense** [comment]
I think I know why this is happening. When a word has a first letter specified (e.g. "y"), it will decide via an rng which letter in the dictionary to pick that starts with "y". However, the seed for the rng is always the same per day.

So, words starting with the same letter will always be the same for any given day, thus leading to this behavior.

**Comment by AlexMassenzio** [comment]
https://github.com/AlexMassenzio/wordchain/blob/06dd1bc6ac0e15139a5e6383ac264c9603fb54ad/src/lib/utils/wordUtils.ts#L10

**Comment by AlexMassenzio** [comment]
Each newly generated word should have a unique seed because of `solvedWords`. Maybe the function calling it is not sending in the right value for solvedWords

**Comment by AlexMassenzio** [comment]
Starting to think today's wordchain was just some crazy luck.

Words ending in Y: 15%
Yield/Other Y words: 16.67%

not impossible so we should keep this open and monitor after tonight's update (v0.7.0)

**Comment by cbouwense** [comment]
it happened again ☠️

**Comment by AlexMassenzio** [comment]
I'll have a fix up tonight to prevent duplicates.

**Comment by cbouwense** [comment]
Something particularly annoying about this is a ton of words in English end in "y", and there are only 6 words in English that are 5 letters, starting with "y". Not necessarily related to this bug but something to keep in mind, filtering out words that end with "y" might be a good idea in the future
