### ISSUE TITLE
Ability to access your results when returning to the website

### ISSUE THREAD

**Issue by westeve** [AlexMassenzio/wordchain#30]
If you complete the wordchain, leave the website and come back, you can press Play and it will tell you that you have already completed today's challenge. You cannot retrieve your results from this screen. A better way to handle this scenario would be to direct you to a screen that looks like the attachment below without having to press the play button:
![completed](https://user-images.githubusercontent.com/39627977/207722053-54a45df9-1cf8-43b8-b9a5-d4a888d08cde.png)

**Comment by AlexMassenzio** [comment]
Thanks for the feedback! This is actually going to be addressed in tonight's update.
