### ISSUE TITLE
Word generation sometimes returns undefined.

### ISSUE THREAD

**Issue by AlexMassenzio** [AlexMassenzio/wordchain#5]
### Describe the bug

`generateWord()` seemed to break the game this morning. Didn't have time to look into the reason, but for the time being I deployed a hotfix with a solution that doesn't involve rng.

The goal of this ticket is to look into the issue with the function and remove the hotfix solution.

### Reproduction

Checkout commit ea9c4a and play the game with your system/browser time set to 12/1/2022.

### System Info

```Shell
Windows and Android, chrome desktop and Firefox app
```

**Comment by AlexMassenzio** [comment]
Above commit was the hotfix to prevent the crash. While we should still have that undefined check in probably, it's still an indicator that there is something wrong with the word generation.

**Comment by cbouwense** [comment]
The code that selects which word in the dictionary to randomly select was asking for an out of bounds array

**Comment by cbouwense** [comment]
This has been fixed
